POST http://localhost:8000/security/login
Content-Type: application/json

{
  "email":"email@email.com",
  "password":"!@test1234"
}

###
GET http://localhost:8000/security/refresh/11
Refresh: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMWVkN2VlOS04YjJlLTRiNmUtODEzNS02ZDJiN2Q5NjJhOTUiLCJpYXQiOjE2NzEzNzc3NTcsImV4cCI6MTY3MTM3OTU1N30.eXM8JXnspDI1aSDnU77-7eDoJQnk3meoARvuQo_yYCVkSAsjexOA-GsaqSHPx3Oqx6SuPLCSniSfVhgsWIzW0w

Content-Type: application/json
