### 주소 조회
GET http://localhost:8080/address?town=우장산

### 계정 생성 (회원가입)
POST http://localhost:8080/account
Content-Type: application/json

< createAccountForm.json

### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginId" : "visitor",
  "password": "visitor1234!@"
}

> {%
client.global.set("access-token", response.headers.valueOf("Authorization"));
client.global.set("refresh-token", response.headers.valueOf("Refresh"));

 %}

### 계정 정보 단건 조회
GET http://localhost:8080/account/1
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwNDk4MTg1LCJleHAiOjE2NzA0OTg3ODV9.ROob_6voHU_iiGzoap4Vdn1rYXdIdjwqm30k2GnKUshDuv1StGCzCpSRri4wRzb73UYsdAVbarAIDXFgCB6xNg
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwNDk4MTg1LCJleHAiOjE2NzA0OTk5ODV9.Ti3M4ZT5SUAC9fLaA3xbNgdSoXqxlKgcnbpP24THmmeoW1y89B7aYlR9aXA32sB0VQC3itxKC2-R2tQJLVaneg

### 계정 정보 리스트 조회
GET http://localhost:8080/account
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwNDY3NTQwLCJleHAiOjE2NzA0NjgxNDB9.sPPNdHSyX6O0J9DIgaoVyDw2AutKeCVPaTve_i8AvgbFUyl_rw1-GAQ8AlPocMBPPjarKQfTEZ0C3bX2rqLF4w
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwNDY3NTQwLCJleHAiOjE2NzA0NjkzNDB9.G8LXX_CX6UJwf3k1lsnGjVwS0ft4v-pDUlV2xmHhwHL3OD_tJK6pJsaCp7ZdtW2nJbUmN1k7zz2bACQeW_SKQA

### 계정 비밀번호 변경
PUT http://localhost:8080/account/1/password
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzAxNDE3NDN9.LiHcJi6ImVMWSk-uhvDtm-nnYmc56ne672dDHICBbyJYhU5TRO6Rz4yjpdvCNKrnaLFZdhza76n53vsoyU_bwQ
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzA3NDQ3NDN9.P2muAhNzZ_26YuB87SDBsSKZ_D34Msj8mxDOsqsE_ua7d6DoN0XYf5dsScnqd3Eda2xWfIyZW9b1G04uhhddfA

{
  "password" : "visitor1234!@",
  "newPassword" : "!@newPassword1234"
}

### 계정 이메일 변경
PUT http://localhost:8080/account/1/email
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzAxNDE3NDN9.LiHcJi6ImVMWSk-uhvDtm-nnYmc56ne672dDHICBbyJYhU5TRO6Rz4yjpdvCNKrnaLFZdhza76n53vsoyU_bwQ
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzA3NDQ3NDN9.P2muAhNzZ_26YuB87SDBsSKZ_D34Msj8mxDOsqsE_ua7d6DoN0XYf5dsScnqd3Eda2xWfIyZW9b1G04uhhddfA

{
  "email" : "newEmail@email.com"
}

### 판매글 생성
POST http://localhost:8080/account/1/trade
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY2LCJleHAiOjE2NzAyNTczNjZ9.bflTtW9yIR2HjHRGXLKZi8HVjMJbmqkj03036cr-QgUNH5__RkbJ7mZyYVjZnaG-ey6vJHbkwSv6z9YE9VNWnw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY3LCJleHAiOjE2NzAyNTg1Njd9.Go7_dasVClpajNFP8mYCBQAaOUBwoZarXVLcNZZJ9W9RhSJcMnRB_h64oYsZ72PkmImDo6qBCin47xlTsIcGvQ
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="IMG_6414.JPG"
Content-Disposition: form-data; name="images"; filename="IMG_6415.JPG"

< ./IMG_6414.JPG
< ./IMG_6415.JPG

--boundary
Content-Disposition: form-data; name="form"; filename="ResultForm.json"
Content-Type: application/json

< createTradeform.json

### 판매글 조회
GET http://localhost:8080/account/1/trade
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY2LCJleHAiOjE2NzAyNTczNjZ9.bflTtW9yIR2HjHRGXLKZi8HVjMJbmqkj03036cr-QgUNH5__RkbJ7mZyYVjZnaG-ey6vJHbkwSv6z9YE9VNWnw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY3LCJleHAiOjE2NzAyNTg1Njd9.Go7_dasVClpajNFP8mYCBQAaOUBwoZarXVLcNZZJ9W9RhSJcMnRB_h64oYsZ72PkmImDo6qBCin47xlTsIcGvQ

Content-Type: application/json


### 판매글 상세 조회
GET http://localhost:8080/trade/101
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY2LCJleHAiOjE2NzAyNTczNjZ9.bflTtW9yIR2HjHRGXLKZi8HVjMJbmqkj03036cr-QgUNH5__RkbJ7mZyYVjZnaG-ey6vJHbkwSv6z9YE9VNWnw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMjU2NzY3LCJleHAiOjE2NzAyNTg1Njd9.Go7_dasVClpajNFP8mYCBQAaOUBwoZarXVLcNZZJ9W9RhSJcMnRB_h64oYsZ72PkmImDo6qBCin47xlTsIcGvQ

Content-Type: application/json

### 판매글 수정
PUT http://localhost:8080/trade/101
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTQzOTA0LCJleHAiOjE2NzAxNDU3MDR9.yJ3EobgISKnTBxpaSAU-EAnGHpd3sWF8QHFCoXJWasKJZWFuJ6eAFl4Fc3fPWjmx77hpuV4jh8RiGmlXBjZmiw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTQzOTA0LCJleHAiOjE2NzA3NDg3MDR9.RmJ98RQKWuWKXxp35m7vl5q1dLhOwpnVSGSPf_uCZp69KSS-EPu2BXRc4LvipjrILLZqDyoxsj-f-NGPaPlc_w
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="IMG_6414.JPG"
Content-Disposition: form-data; name="images"; filename="IMG_6415.JPG"

< ./IMG_6414.JPG
< ./IMG_6415.JPG

--boundary
Content-Disposition: form-data; name="form"; filename="ResultForm.json"
Content-Type: application/json

< tradeUpdateForm.json


### 판매글 삭게
DELETE http://localhost:8080/trade/101
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTQzOTA0LCJleHAiOjE2NzAxNDU3MDR9.yJ3EobgISKnTBxpaSAU-EAnGHpd3sWF8QHFCoXJWasKJZWFuJ6eAFl4Fc3fPWjmx77hpuV4jh8RiGmlXBjZmiw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTQzOTA0LCJleHAiOjE2NzA3NDg3MDR9.RmJ98RQKWuWKXxp35m7vl5q1dLhOwpnVSGSPf_uCZp69KSS-EPu2BXRc4LvipjrILLZqDyoxsj-f-NGPaPlc_w
Content-Type: multipart/form-data; boundary=boundary