### 주소 조회
GET http://localhost:8080/address?town=화곡


### 계정 생성 (회원가입)
POST http://localhost:8080/account
Content-Type: application/json

{
  "loginId" : "visitor",
  "name" : "홍길동",
  "nickname" : "미스터홍",
  "password" : "visitor1234!@",
  "email" : "visitor@visitor.com",
  "contact" : "01099990000",
  "addressCode" : 1001,
  "city" : "서울",
  "district" : "서울구",
  "town" : "서울동"
}



### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginId" : "visitor",
  "password": "visitor1234!@"
}

> {%
client.global.set("access-token", response.headers.valueOf("Authorization"));
client.global.set("refresh-token", response.headers.valueOf("Refresh"));

 %}

### 계정 정보 단건 조회
GET http://localhost:8080/account/1
Content-Type: application/json


### 계정 정보 리스트 조회
GET http://localhost:8080/account
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDU4MjF9.CxxKKf8p6QwZ3oOw93pztuLOIjJi0L1IP000MHA_I2iqHhchfia2RWAxb2P8UQn7LJkcnoKhHdJT9CPp-UGDBw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDcwMjF9.NoQK8whhCxgLKOjAf-492ccvnFyB0MnL3md07-4Dzr_EoV9nh-siw8SpuL1l2iHyfN-IE0A0GBieobFXz1DOCA

### 계정 비밀번호 변경
PUT http://localhost:8080/account/1/password
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDU4MjF9.CxxKKf8p6QwZ3oOw93pztuLOIjJi0L1IP000MHA_I2iqHhchfia2RWAxb2P8UQn7LJkcnoKhHdJT9CPp-UGDBw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDcwMjF9.NoQK8whhCxgLKOjAf-492ccvnFyB0MnL3md07-4Dzr_EoV9nh-siw8SpuL1l2iHyfN-IE0A0GBieobFXz1DOCA

{
  "password" : "visitor1234!@",
  "newPassword" : "!@newPassword1234"
}

### 계정 이메일 변경
PUT http://localhost:8080/account/1/email
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzAxNDE3NDN9.LiHcJi6ImVMWSk-uhvDtm-nnYmc56ne672dDHICBbyJYhU5TRO6Rz4yjpdvCNKrnaLFZdhza76n53vsoyU_bwQ
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM5OTQzLCJleHAiOjE2NzA3NDQ3NDN9.P2muAhNzZ_26YuB87SDBsSKZ_D34Msj8mxDOsqsE_ua7d6DoN0XYf5dsScnqd3Eda2xWfIyZW9b1G04uhhddfA

{
  "email" : "newEmail@email.com"
}

### 판매글 생성
POST http://localhost:8080/account/1/trade
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDU4MjF9.CxxKKf8p6QwZ3oOw93pztuLOIjJi0L1IP000MHA_I2iqHhchfia2RWAxb2P8UQn7LJkcnoKhHdJT9CPp-UGDBw
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1MjIxLCJleHAiOjE2NzA5NDcwMjF9.NoQK8whhCxgLKOjAf-492ccvnFyB0MnL3md07-4Dzr_EoV9nh-siw8SpuL1l2iHyfN-IE0A0GBieobFXz1DOCA
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="IMG_6414.JPG"
Content-Disposition: form-data; name="images"; filename="IMG_6415.JPG"

< ./IMG_6414.JPG
< ./IMG_6415.JPG

--boundary
Content-Disposition: form-data; name="form"; filename="ResultForm.json"
Content-Type: application/json

< createTradeform.json

### 판매글 조회
GET http://localhost:8080/account/1/trade
Authorization: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDY1MzR9.Lzuxa5ios0UPGf0BVWIPSp133Dh3L31xN62g5TsfnMpxEQYdH43V3gNJrL1EMLYN7DznBl_Ej-d8wh3lqz29tw
Refresh: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDc3MzR9.yOc553pxPyKzErYzTZahYFc5VCatMnK41PLKnJ6pyEZ96wAGLDhGdvRCR-RMJV8vqz-BxNiCtBAp0hDjzCufvQ

Content-Type: application/json


### 판매글 상세 조회
GET http://localhost:8080/trade/101
Authorization: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDY1MzR9.Lzuxa5ios0UPGf0BVWIPSp133Dh3L31xN62g5TsfnMpxEQYdH43V3gNJrL1EMLYN7DznBl_Ej-d8wh3lqz29tw
Refresh: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDc3MzR9.yOc553pxPyKzErYzTZahYFc5VCatMnK41PLKnJ6pyEZ96wAGLDhGdvRCR-RMJV8vqz-BxNiCtBAp0hDjzCufvQ

Content-Type: application/json

### 판매글 수정
PUT http://localhost:8080/trade/101
Authorization: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDY1MzR9.Lzuxa5ios0UPGf0BVWIPSp133Dh3L31xN62g5TsfnMpxEQYdH43V3gNJrL1EMLYN7DznBl_Ej-d8wh3lqz29tw
Refresh: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDc3MzR9.yOc553pxPyKzErYzTZahYFc5VCatMnK41PLKnJ6pyEZ96wAGLDhGdvRCR-RMJV8vqz-BxNiCtBAp0hDjzCufvQ
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="IMG_6414.JPG"
Content-Disposition: form-data; name="images"; filename="IMG_6415.JPG"

< ./IMG_6414.JPG
< ./IMG_6415.JPG

--boundary
Content-Disposition: form-data; name="form"; filename="ResultForm.json"
Content-Type: application/json

< tradeUpdateForm.json


### 판매글 삭제
DELETE http://localhost:8080/trade/101
Authorization: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDY1MzR9.Lzuxa5ios0UPGf0BVWIPSp133Dh3L31xN62g5TsfnMpxEQYdH43V3gNJrL1EMLYN7DznBl_Ej-d8wh3lqz29tw
Refresh: Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwOTQ1OTM0LCJleHAiOjE2NzA5NDc3MzR9.yOc553pxPyKzErYzTZahYFc5VCatMnK41PLKnJ6pyEZ96wAGLDhGdvRCR-RMJV8vqz-BxNiCtBAp0hDjzCufvQ
Content-Type: multipart/form-data; boundary=boundary