### 계정 생성 (회원가입)
POST http://localhost:8080/account
Content-Type: application/json

< createAccountForm.json


### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginId" : "visitor",
  "password": "visitor1234!@"
}

> {%
client.global.set("access-token", response.headers.valueOf("Authorization"));
client.global.set("refresh-token", response.headers.valueOf("Refresh"));

 %}

###
GET http://localhost:8080/account/1
Content-Type: application/json
Authorization:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM2ODE2LCJleHAiOjE2NzAxMzg2MTZ9.Je3YCLgB18HGuvvMdwTdZAiEcZYYhtfTyeAD3_uPSX-UKcxmIlSwWwGgwRjXpdCfmQOa5aLj8Rdn7P8WF2CLew
Refresh:Bearer-eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjcwMTM2ODE2LCJleHAiOjE2NzA3NDE2MTZ9.pjFbzVC7cMlfJp39bGbd9SnyTsSXBxpVceKeqNnHzLf4AQcYi1BCXDrNSF3DjCkK7bYNz-P9XPjP2SeuVgtMUg


