
### 프로필 이미지 생성
POST http://localhost:8095/frm/account/1/profile




### 프로필 이미지 수정
PUT http://localhost:8095/frm/account/1/profile
Content-Type: multipart/form-data;  boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="IMG_6418.JPG"

< ./IMG_6418.JPG


###
DELETE http://localhost:8095/frm/account/1/profile

