server:
  port: 8095

resource-path:
  url-pattern: http://localhost:8095/file/
  path-pattern: /file/**
  location-path: file:///Users/leechoongsub/desktop/msa-project/frm/
  profile-image-path: /Users/leechoongsub/desktop/msa-project/frm/profile-images/
  trade-image-path: /Users/leechoongsub/desktop/msa-project/frm/trade-images/



spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: file-resource-management
