server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: address
  config:
    activate:
      on-profile: test
---
server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: address
  config:
    activate:
      on-profile: prod