server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/login
            - Method=POST
          filters:
            - CustomFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/security/(?<segment>.*),/$\{segment}
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/account
            - Method=POST
          filters:
            - CustomFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/security/(?<segment>.*),/$\{segment}
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/refresh/**
            - Method=GET
          filters:
            - CustomFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/security/(?<segment>.*),/$\{segment}
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/security/(?<segment>.*),/$\{segment}
            - GateWayAuthorizationFilter

custom-key:
  secret-key: MySecreteKeyIsMySecreteKeyItIsMustBeGreaterThen512bits
